"use strict";
exports.__esModule = true;
exports.populateFromJson = void 0;
var user_1 = require("./user");
function populateFromJson(tr, i) {
    var cell1 = tr.insertCell(-1);
    var id = user_1.users.items[i].id;
    cell1.innerHTML = id;
    cell1.id = "row" + (i) + "Id";
    var cell2 = tr.insertCell(-1);
    var fname = user_1.users.items[i].firstName;
    cell2.innerHTML = fname;
    cell2.id = "row" + (i) + "Fname";
    var cell3 = tr.insertCell(-1);
    var mname = user_1.users.items[i].middleName;
    ;
    cell3.innerHTML = mname;
    cell3.id = "row" + (i) + "Mname";
    var cell4 = tr.insertCell(-1);
    var lname = user_1.users.items[i].lastName;
    cell4.innerHTML = lname;
    cell4.id = "row" + (i) + "Lname";
    var cell5 = tr.insertCell(-1);
    var email = user_1.users.items[i].email;
    cell5.innerHTML = email;
    cell5.id = "row" + (i) + "Email";
    var cell6 = tr.insertCell(-1);
    var phone = user_1.users.items[i].phoneNumber;
    cell6.innerHTML = phone;
    cell6.id = "row" + (i) + "Phone";
    var cell7 = tr.insertCell(-1);
    var role = user_1.users.items[i].role;
    cell7.innerHTML = role;
    cell7.id = "row" + (i) + "Role";
    var cell8 = tr.insertCell(-1);
    var add = user_1.users.items[i].address;
    cell8.innerHTML = add;
    cell8.id = "row" + (i) + "Address";
    cell1.className = "editable";
    cell2.className = "editable";
    cell3.className = "editable";
    cell4.className = "editable";
    cell5.className = "editable";
    cell6.className = "editable";
    cell7.className = "editable";
    cell8.className = "editable";
}
exports.populateFromJson = populateFromJson;
